server:
  port: 80

mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: top.theanything.forum.pojo

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhou?useUnicode=true&characterEncoding=UTF-8
    password: 1234
    username: root
    name: info
    #使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

bbs:
  encryption:
    seed: 0x3f2a3c7e
    salt: xzcawx
top:
  jedis:
    host: localhost
    port: 6379
    select: 10
    MAX_IDLE: 10
    MAX_WAITMILLIS:

